apiVersion: v1
kind: Service
metadata:
  name: petclinic-lb
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
    - port: 8181
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
    tags.datadoghq.com/version: "1.0.26"
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "petclinic"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
        tags.datadoghq.com/version: "1.0.26"
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "petclinic"
      annotations:
        ad.datadoghq.com/spring-container.logs: '[{"source":"java","service":"petclinic","log_processing_rules":[{"type":"multi_line","name":"log_start_with_date","pattern":"\\{\"timestamp\""}]}]'
    spec:
      containers:
        - name: spring-container
          image: samuelblin/petclinic:1.0.26
          ports:
            - containerPort: 8080
          env:
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          - name: DD_GIT_COMMIT_SHA
            value: 6495497af0c9e51bdca0f3e69456c1013d818814
          - name: DD_GIT_REPOSITORY_URL
            value: https://github.com/sblin-datadog/spring-petclinic
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_ORIGIN_DETECTION_ENABLED
            value: "false"